# Generated by Django 4.2 on 2024-12-24 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_watched', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_movies', to='users.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='movie_watches',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='users.moviewatch'),
        ),
    ]
