# Generated by Django 4.2 on 2024-12-24 13:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_moviewatch_userprofile_movie_watches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='movie_watches',
        ),
        migrations.AddField(
            model_name='moviewatch',
            name='watched_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moviewatch',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_watches', to='users.userprofile'),
        ),
    ]
