# Generated by Django 4.2 on 2024-12-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_movie_watches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviewatch',
            name='watched_at',
            field=models.DateTimeField(),
        ),
    ]
