# Generated by Django 4.2 on 2024-12-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_moviewatch_watched_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviewatch',
            old_name='is_watched',
            new_name='is_finished',
        ),
    ]
