# Generated by Django 4.2 on 2025-01-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_is_watched_moviewatch_is_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviewatch',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='moviewatch',
            name='rating',
            field=models.IntegerField(choices=[(-1, 'Disliked'), (0, 'Neutral'), (1, 'Liked')], default=0),
        ),
    ]
