# Generated by Django 4.2 on 2025-01-11 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_moviewatch_user_profile_moviewatch_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviewatch',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movie_watches', to='users.userprofile'),
            preserve_default=False,
        ),
    ]
