# Generated by Django 4.2 on 2025-01-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_moviewatch_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='disliked_movies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='liked_movies',
        ),
    ]
