# Generated by Django 4.2 on 2025-01-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_userprofile_disliked_movies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='priority_movies_recommendations_dictionary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
