# Generated by Django 4.2 on 2024-12-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=11)),
                ('movie_name', models.TextField()),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('certificate', models.CharField(max_length=16)),
                ('runtime', models.IntegerField()),
                ('rating', models.FloatField()),
                ('votes', models.IntegerField()),
                ('directors', models.ManyToManyField(blank=True, to='main.moviedirector')),
                ('genres', models.ManyToManyField(blank=True, to='main.moviegenre')),
                ('stars', models.ManyToManyField(blank=True, to='main.moviestar')),
            ],
        ),
    ]
