# Generated by Django 4.2 on 2024-12-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='certificate',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.TextField(),
        ),
    ]
