# Generated by Django 4.2 on 2025-01-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='moviedirector',
            name='name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='moviestar',
            name='name',
            field=models.TextField(db_index=True),
        ),
    ]
